# Generated for Joomla Partners Control.
import django.db.models.deletion
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="ClientSite", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=200, verbose_name="Название")), ("domain", models.CharField(max_length=500, unique=True, verbose_name="Домен / URL")), ("logo", models.ImageField(blank=True, upload_to="client_logos/", verbose_name="Логотип")), ("default_html", models.TextField(blank=True, verbose_name="HTML")), ("enabled", models.BooleanField(default=True, verbose_name="Активен")), ("notes", models.TextField(blank=True, verbose_name="Заметки"))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="PageTemplate", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=150, verbose_name="Название")), ("slug", models.SlugField(unique=True)), ("wrapper_html", models.TextField(default='<ul class="partners">\n{{ items }}\n</ul>')), ("item_html", models.TextField(default='<li>\n <div class="Img"><a href="{{ url }}"{{ link_attributes }}><img src="{{ image }}" alt="{{ client_name }}"></a></div>\n <div class="txt">{{ client_html }}</div>\n <div class="Clear"></div>\n</li>')), ("css", models.TextField(blank=True)), ("include_css_in_article", models.BooleanField(default=False, verbose_name="Добавлять CSS в материал")), ("enabled", models.BooleanField(default=True, verbose_name="Активен")), ("version", models.PositiveIntegerField(default=1))]),
        migrations.CreateModel(name="DonorSite", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=200, verbose_name="Название")), ("domain", models.CharField(max_length=253, unique=True, verbose_name="Домен")), ("admin_url", models.URLField(max_length=500, verbose_name="Admin URL")), ("page_url", models.URLField(max_length=500, verbose_name="URL страницы партнёров")), ("joomla_version", models.CharField(choices=[("unknown", "Неизвестна"), ("3", "Joomla 3"), ("4", "Joomla 4"), ("5", "Joomla 5")], default="unknown", max_length=10, verbose_name="Версия Joomla")), ("username", models.CharField(blank=True, max_length=150, verbose_name="Логин")), ("encrypted_password", models.TextField(blank=True, editable=False)), ("article_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="ID материала")), ("menu_item_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="ID пункта меню")), ("article_alias", models.SlugField(blank=True, max_length=255, verbose_name="Alias")), ("enabled", models.BooleanField(default=True, verbose_name="Активен")), ("connection_status", models.CharField(choices=[("unknown", "Не проверено"), ("online", "Online"), ("error", "Ошибка"), ("not_implemented", "Не реализовано")], default="unknown", max_length=30)), ("last_checked_at", models.DateTimeField(blank=True, null=True)), ("last_published_at", models.DateTimeField(blank=True, null=True)), ("notes", models.TextField(blank=True, verbose_name="Заметки")), ("managed_marker_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)), ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="partners.pagetemplate", verbose_name="Шаблон"))], options={"ordering": ["domain"]}),
        migrations.CreateModel(name="Placement", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("position", models.PositiveIntegerField(default=0)), ("enabled", models.BooleanField(default=True)), ("html_override", models.TextField(blank=True)), ("url_override", models.URLField(blank=True, max_length=500)), ("image_override", models.URLField(blank=True, max_length=500)), ("target_blank", models.BooleanField(default=False)), ("nofollow", models.BooleanField(default=False)), ("sponsored", models.BooleanField(default=False)), ("client", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="placements", to="partners.clientsite")), ("donor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="placements", to="partners.donorsite"))], options={"ordering": ["position", "id"], "constraints": [models.UniqueConstraint(fields=("donor", "client"), name="unique_donor_client")]}),
        migrations.CreateModel(name="PublicationLog", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("action", models.CharField(choices=[("preview", "Предпросмотр"), ("connection_test", "Проверка подключения"), ("publish", "Публикация"), ("create_article", "Создание материала"), ("update_article", "Обновление материала"), ("trash_article", "В корзину"), ("restore_article", "Восстановление")], max_length=30)), ("status", models.CharField(choices=[("success", "Успешно"), ("error", "Ошибка"), ("not_implemented", "Не реализовано")], max_length=30)), ("message", models.TextField(blank=True)), ("generated_html_hash", models.CharField(blank=True, max_length=64)), ("response_code", models.PositiveIntegerField(blank=True, null=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("donor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publication_logs", to="partners.donorsite"))], options={"ordering": ["-created_at"]}),
    ]
